name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.gitea/workflows/lint.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Deploy Website
        uses: https://github.com/nekiro/ssh-job@main
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          command: |
            cd /var/www/crss
            git pull
            composer install --no-dev --optimize-autoloader
            php .scripts/deploy.php