name: ️Upload Website

on: [ push ]

jobs:
  sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: https://github.com/wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          forceUpload: true
          localDir: '.'
          remoteDir: '/var/www/crss'
          exclude: '.git,.git*,.env.*,LICENSE,README.md'