name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9
      - name: Lint
        run: |
          pnpm install
          pnpm lint
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Deploy Over SSH
        uses: nekiro/ssh-job@main
        with:
          host: ${{ secrets.HOST }}
          user: crss
          password: ${{ secrets.DEPLOY_PASSWORD }}
          command: |
            cd ~/crss
            git pull
            ~/.local/share/pnpm/pnpm install
            ~/.local/share/pnpm/pnpm build
            sudo systemctl restart crss.service
