name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Deploy Over SSH
        uses: nekiro/ssh-job@main
        with:
          host: ${{ secrets.HOST }}
          user: crss
          password: ${{ secrets.DEPLOY_PASSWORD }}
          command: |
            cd ~/crss
            git pull
            ~/.local/share/pnpm/pnpm install
            ~/.local/share/pnpm/pnpm build
            sudo systemctl restart crss.service
